# Copyright (C) 2016-2024 Simon Josefsson

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH

default:
  interruptible: true
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - "*.tar.gz"
    - ./*.log
    - ./config.h
    - ./**/*.log
    - website/html
    - coverage
    - clang-analyzer

stages:
 - build
 - test
 - deploy

sast:
  stage: build
  variables:
    SAST_EXCLUDED_PATHS: oathtool/gl, pskctool/gl, liboath/gl, libpskc/gl
include:
- template: Security/SAST.gitlab-ci.yml

B-gcc:
  image: gcc:latest
  stage: build
  before_script:
  - gcc --version
  - apt-get update -qq
  - apt-get install -y -qq make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt datefudge
  script:
  - gcc --version
  - ./bootstrap
  - ./configure CC="gcc -std=gnu2x" --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - git status
  - git diff --exit-code

B-clang:
  image: silkeh/clang:latest
  stage: build
  before_script:
  - clang --version
  - apt-get update -qq
  - apt-get install -y -qq make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt faketime
  script:
  - clang --version
  - ./bootstrap
  - ./configure CC="clang -std=gnu2x" --enable-gcc-warnings WARN_CFLAGS=-Werror
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - git status
  - git diff --exit-code

B-Trisquel11:
  image: registry.gitlab.com/oath-toolkit/build-images:Trisquel11
  stage: build
  before_script:
  - apt-get remove -y -qq --purge indent
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - ./bootstrap
  - ./configure -C --enable-gtk-doc --enable-gtk-doc-pdf --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - make -j$(nproc) dist
  - sha224sum oath-toolkit-*.tar.gz
  - cd website && ./build-website.sh

B-Debian13-arm64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: debian:trixie-slim
  tags: [ saas-linux-medium-arm64 ]
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt indent
  script:
  - ./bootstrap
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t

B-Ubuntu2204-ppc64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: ubuntu:22.04
  tags: [ ppc64 ]
  stage: build
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make git autoconf automake libtool bison libpam0g-dev libxmlsec1-dev libxml2-utils help2man gtk-doc-tools gengetopt
  script:
  - ./bootstrap
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 check VERBOSE=t

B-Debian12-coverage:
  image: registry.gitlab.com/oath-toolkit/build-images:Debian12-coverage
  stage: build
  script:
  - echo "--suppressions=$(pwd)/libpskc/tests/libpskc.supp" >> ~/.valgrindrc
  - ./bootstrap
  - ./configure --enable-gcc-warnings --enable-root-tests --enable-valgrind-tests CFLAGS="-g --coverage"
  - lcov --directory . --zerocounters
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_usersfile.sh' liboath/tests/tst_usersfile.log
  - grep '^PASS run-root-tests.sh' pam_oath/tests/run-root-tests.sh.log
  - mkdir coverage
  - lcov --directory . --output-file coverage/oath-toolkit.info --capture
  - lcov --remove coverage/oath-toolkit.info '/usr/include/*' '*/liboath/gl/*' '*/liboath/tests/*' '*/libpskc/gl/*' '*/libpskc/tests/*' '*/oathtool/gl/*' '*/pam_oath/tests/*' '*/pskctool/gl/*' -o coverage/oath-toolkit_filtered.info
  - genhtml --output-directory coverage coverage/oath-toolkit_filtered.info --highlight --frames --legend --title "OATH Toolkit"

B-Fedora39-clanganalyzer:
  image: registry.gitlab.com/oath-toolkit/build-images:Fedora39-clanganalyzer
  stage: build
  script:
  - ./bootstrap
  - scan-build ./configure --with-xmlsec-crypto-engine=openssl
  - scan-build -o clang-analyzer make -j$(nproc) V=1

# https://docs.gitlab.com/ee/ci/runners/saas/macos/environment.html
B-macOS14Xcode15:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: macos-14-xcode-15
  tags: [ saas-macos-medium-m1 ]
  stage: build
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  before_script:
  - brew install autoconf automake libtool gengetopt bison gtk-doc help2man libxmlsec1
  script:
  - PATH="/opt/homebrew/opt/bison/bin:$PATH" # brew bison is keg-only
  - ./bootstrap
  - ./configure --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1
  - make -j$(nproc) V=1 -k check VERBOSE=t
  - git status
  - git restore liboath/gtk-doc.make libpskc/gtk-doc.make
  - git diff --exit-code

# https://docs.gitlab.com/ee/ci/runners/saas/windows_saas_runner.html
B-Windows-UCRT64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: build
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe --no-check-certificate -nv -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'UCRT64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu git autoconf automake libtool make mingw-w64-ucrt-x86_64-gcc bison gtk-doc gengetopt help2man
    # https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
    file configure.ac
    git config --global core.autocrlf false
    git config --global core.eol lf
    git rm -rf --cached . | tail
    git reset --hard HEAD
    file configure.ac
    ./bootstrap
    ./configure -C --enable-gcc-warnings
    make -j$(nproc) V=1 -k check VERBOSE=t'

# https://www.synopsys.com/blogs/software-security/integrating-coverity-scan-with-gitlab-ci/
Coverity:
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"
  - when: manual
  image: registry.gitlab.com/oath-toolkit/build-images:Debian12-coverage
  stage: build
  allow_failure: true
  before_script:
  - apt-get update -qq -y
  - apt-get install -y -q curl
  script:
  - test -n "$COVERITY_SCAN_TOKEN" && test -n "$COVERITY_SCAN_PROJECT_NAME"
  - curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64
    --form project="$COVERITY_SCAN_PROJECT_NAME" --form token="$COVERITY_SCAN_TOKEN"
  - md5sum /tmp/cov-analysis-linux64.tgz
  - tar xfz /tmp/cov-analysis-linux64.tgz
  - time ./bootstrap --skip-po
  - time ./configure --enable-gcc-warnings --disable-doc --enable-root-tests CFLAGS="-g -Og"
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make check -j$(nproc)
  - tar cfz cov-int.tar.gz cov-int
  - curl https://scan.coverity.com/builds
    --form project="$COVERITY_SCAN_PROJECT_NAME"
    --form token="$COVERITY_SCAN_TOKEN" --form email="$GITLAB_USER_EMAIL"
    --form file=@cov-int.tar.gz --form version="`git describe --tags`"
    --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID"
  artifacts:
    expire_in: 1 week
    paths:
      - cov-int/*.txt

Windows-MSYS:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: test
  needs: [B-Trisquel11]
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe --no-check-certificate -nv -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MSYS' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu make gcc
    tar xfa oath-toolkit-*.tar.gz
    cd `ls -d oath-toolkit-* | grep -v tar.gz`
    ./configure -C --enable-gcc-warnings
    make -j$(nproc) V=1 -k check VERBOSE=t'

Windows-MINGW64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: test
  needs: [B-Trisquel11]
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe --no-check-certificate -nv -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu make mingw-w64-x86_64-gcc
    tar xfa oath-toolkit-*.tar.gz
    cd `ls -d oath-toolkit-* | grep -v tar.gz`
    ./configure -C --enable-gcc-warnings
    make -j$(nproc) V=1 -k check VERBOSE=t'

Debian12:
  image: debian:12-slim
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Ubuntu2310-xmlsec-ppc64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: ubuntu:23.10
  tags: [ ppc64 ]
  stage: test
  needs: [B-Trisquel11]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure -C --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Ubuntu-xmlsec:
  image: ubuntu:20.04
  stage: test
  needs: [B-Trisquel11]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make gcc pkg-config libpam0g-dev libxmlsec1-dev libxml2-utils datefudge
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings --disable-valgrind-tests
  - make -j$(nproc) check V=1 VERBOSE=t

AlmaLinux8-xmlsec:
  image: almalinux:8
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - yum -y install make gcc diffutils file pam-devel
  - yum -y install libxml2-devel libtool-ltdl-devel
  - dnf -y install epel-release
  - dnf -y --enablerepo=powertools install indent xmlsec1-openssl-devel
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure -C --enable-gcc-warnings --disable-valgrind-tests --with-xmlsec-crypto-engine=openssl
  - make -j$(nproc) syntax-check
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

RockyLinux9-ppc64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: rockylinux:9
  tags: [ ppc64 ]
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - dnf -y install make gcc diffutils file pam-devel
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

Alpine-mold:
  image: alpine:latest
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - apk update
  - apk add build-base datefudge xmlsec-dev mold
  script:
  - tar xfz oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure -C --enable-gcc-warnings CC='cc -fuse-ld=mold'
  - make -j$(nproc) check V=1 VERBOSE=t 2>&1 | tee build.log
  - (! grep -E 'mold. warning' build.log)
  - grep 'mold ' libpskc/.libs/libpskc.so

Alpine-arm64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: alpine:latest
  tags: [ saas-linux-medium-arm64 ]
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - apk update
  - apk add build-base datefudge xmlsec-dev
  script:
  - tar xfz oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

ArchLinux-xmlsec:
  image: archlinux:latest
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - pacman -Suy --noconfirm make gcc diffutils file xmlsec pkg-config
  script:
  - tar xfz oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t
  - grep '^PASS tst_pskctool' pskctool/tests/tst_pskctool.sh.log

Fedora39-arm64:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: fedora:39
  tags: [ saas-linux-medium-arm64 ]
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - dnf install -y make gcc diffutils file pam-devel
  - dnf install -y libxml2-devel xmlsec1-devel xmlsec1-openssl libtool-ltdl-devel
  script:
  - tar xfz oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure -C --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

Gentoo:
  image: registry.gitlab.com/oath-toolkit/build-images:Gentoo
  stage: test
  needs: [B-Trisquel11]
  script:
  - tar xfz oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make -j$(nproc) check V=1 VERBOSE=t

macOS13Xcode14:
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: manual
  image: macos-13-xcode-14
  tags: [ saas-macos-medium-m1 ]
  stage: test
  needs: [B-Trisquel11]
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  before_script:
  - brew install libxmlsec1
  script:
  - gzip -cd oath-toolkit-*.tar.gz | tar xf -
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1 check VERBOSE=t

Mingw32:
  image: debian:11-slim
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - dpkg --add-architecture i386
  - apt-get update -qq
  - apt-get install -y -qq make mingw-w64 wine wine32 wine64 libwine libwine:i386 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure --host=i686-w64-mingw32 CC='i686-w64-mingw32-gcc -static-libgcc'
  - make -j$(nproc) V=1
  - make -j$(nproc) -C liboath/tests check VERBOSE=t
  - make -j$(nproc) -C oathtool/tests check VERBOSE=t

Mingw64:
  image: debian:11-slim
  stage: test
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - apt-get install -y -qq make mingw-w64 wine wine64 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  script:
  - tar xfa oath-toolkit-*.tar.gz
  - cd `ls -d oath-toolkit-* | grep -v tar.gz`
  - ./configure --host=x86_64-w64-mingw32
  - make -j$(nproc) V=1
  - make -j$(nproc) -C liboath/tests check VERBOSE=t
  - make -j$(nproc) -C oathtool/tests check VERBOSE=T

.pages:
  stage: deploy
  needs: ["B-Trisquel11", "B-Debian12-coverage", "B-Fedora39-clanganalyzer"]
  script:
  - mkdir public
  - mv coverage/ public/
  - mv clang-analyzer/* public/clang-analyzer
  - mv website/html/* public/
  artifacts:
    paths:
    - public
    expire_in: 30 days

pages:
  extends: .pages
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"

pages-test:
  extends: .pages
  rules:
  - if: $CI_COMMIT_REF_PROTECTED != "true"
