#!/bin/sh

# Copyright (C) 2023-2024 Simon Josefsson

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

printf "gdoc_MANS =\ngdoc_TEXINFOS =\n" > liboath/man/Makefile.gdoc
printf "gdoc_MANS =\ngdoc_TEXINFOS =\n" > libpskc/man/Makefile.gdoc

touch ChangeLog

gnulib-tool --import \
  --lib=libgnu \
  --source-base=gl \
  --m4-base=gl/m4 \
  --doc-base=doc \
  --tests-base=gl/tests \
  --aux-dir=build-aux \
  --no-conditional-dependencies \
  --no-libtool \
  --macro-prefix=gl \
  --no-vc-files \
  autobuild \
  git-version-gen \
  gitlog-to-changelog \
  maintainer-makefile \
  update-copyright

cd liboath && gnulib-tool --import \
  --local-dir=gl/override \
  --lib=libgnu \
  --source-base=gl \
  --m4-base=gl/m4 \
  --doc-base=doc \
  --tests-base=gl/tests \
  --aux-dir=build-aux \
  --lgpl=2 \
  --no-conditional-dependencies \
  --libtool \
  --macro-prefix=gl \
  base32 \
  c-ctype \
  crypto/gc-hmac-sha1 \
  crypto/gc-hmac-sha256 \
  crypto/gc-hmac-sha512 \
  fclose \
  fopen-gnu \
  fseeko \
  fsync \
  getline \
  lib-symbol-versions \
  lib-symbol-visibility \
  manywarnings \
  rename \
  snprintf \
  strdup-posix \
  strptime \
  strtok_r \
  strverscmp \
  sys_stat \
  unlink \
  valgrind-tests

autoreconf --force --install
